import { course_images } from "./images"

const courses = [
    {
        id: "xMHCZL",
        category: "python",
        image: course_images.python5,
        course_name: "Learn Python: The Complete Python Programming Course",
        description: "Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Avinash Jain, The Codex",
        updated_date: "9/2024",
        lang: "english",
        actual_price: "30,000",
        discounted_price: 4500,
        what_you_will_learn: [
            "create their own Python Programs",
            "Become an experienced Python Programmer",
            "Parse the web and Create their own Games"
        ],
        content: [
            "Up and Running With Python",
            "The Basics(Data Types)",
            "Conditions and Loops",
            "Functions!",
            "Classes! (Object Oriented Programming",
            "File Input/Output",
            "Using Python Modules"
        ]
    },
    {
        id: "dtfo9e",
        category: "python",
        image: course_images.python4,
        course_name: "Learning Python for Data Analysis and Visualization",
        description: "Learn python and how to use it to analyze, visualize, and present data. Includes tons of sample code and hours of video!",
        rating_count: 3059,
        rating_star: 4.3,
        students: 184053,
        creator: "Jose Portilla",
        updated_date: "9 / 2023",
        lang: "english",
        actual_price: "25,000",
        discounted_price: 4500,
        what_you_will_learn: [
            "Have an intermediate skill level of Python Programming.",
            "Use the numpy library to create and manipulate arrays",
            "Learn how to work with various data formats within python, including: JSON, HTML, and MS Excel Worksheets.",
            "Have a portfolio of various data analysis projects"
        ],
        content: [
            "Intro to Course and Python",
            "Learning Numpy",
            "Data Visualisation",
            "Example Projects",
            "Machine Learning",
            "SQL and Python",
            "Web Scraping with Python"
        ]
    },
    {
        id: "flrow6",
        category: "python",
        image: course_images.python3,
        course_name: "Python for Beginners - Learn Programming from scratch",
        description: "Python for Beginners : This course is meant for absolute beginners in programming or in python",
        rating_count: 1844,
        rating_star: 4.3,
        students: 7330,
        creator: "Edwin Diaz, Coding Faculty Solutions",
        updated_date:" 5 / 2023",
        lang: "english",
        actual_price: "25,000",
        discounted_price: 4000,
        what_you_will_learn: [
            "To learn the python language",
            "To learn the CORE skills to understand any programming language"
        ],
        content: [
            "Programming fundamentals",
            "Getting Started with python",
            "Python Basics",
            "Conditional structures",
            "Functions",
            "Working with files"
        ]
    },
    {
        id: "VwKN_o",
        category: "python",
        image: course_images.python2,
        course_name: "Python for beginners : This course is the meant for absolute beginners in programming or in python.",
        description: "Python introduction for beginners. Learn complete Python from scratch!",
        rating_count: 2780,
        rating_star: 4.3,
        students: 29082,
        creator:" Abrar Hussain",
        updated_date:" 6/2024",
        lang: "english",
        actual_price: "30,000",
        discounted_price: 4500,
        what_you_will_learn: [
            "Create fully functional Python programs",
            "Learn about loop structures and conditionals",
            "Work with Python file handling"
        ],
        content: [
            "Getting Started",
            "The Basics",
            "User Input",
            "Functions and files",
            "Classes and Object ",
            "Graphics and Animations"
        ]
    },
    {
        id: "xJB-WU",
        category: "python",
        image: course_images.python1,
        course_name: "Python Beyond the Basics - Object-Oriented Programming",
        description: "From Classes To Inheritance - OOP In-Depth For Python Programmers",
        rating_count: 2941,
        rating_star: 4.2,
        students: 10450,
        creator: "Infinite Skills",
        updated_date: "9/2024",
        lang: "english",
        actual_price: "40,000",
        discounted_price: 10000,
        what_you_will_learn: [
            "Design Reusable Object-Oriented Python Classes",
            "How to handle Errors",
            "Work with Python file handling",
            "Apply OOP Concepts to handle complexity"
        ],
        content : [
            "Introduction to Object Oriented Pyhton",
            "Classes",
            "Inheritance and Polymorphism",
            "Advanced Features",
            "Object Serialization",
            "Effiency and testing",
            "Conclusion"
        ]
    },
    {
        id: "qjdYG4",
        category: "Web development",
        image: course_images.web_dev1,
        course_name: "Become a Certified HTML, CSS, Javascript Web Developer",
        description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
        rating_count: 2760,
        rating_star: 4.1,
        students: 33455,
        creator: "Tech Learning Network, Mark Lassof",
        updated_date: "11/2023",
        lang: "english",
        actual_price: "30,000",
        discounted_price: 5000,
        what_you_will_learn: [
            "Prepare for Industry Certification Exam",
            "Hours and Hours of Video Instruction",
            "Over 25 Engaging Lab Exercises",
            "Instructor Available by Email or on the forums"
        ],
        content: [
            "Your Development Toolbox",
            "Certified HTML5 Specialist 2019",
            "Certified CSS Specialist 2019",
            "Javascript SPecialist 2019",
            "jQuery for Application Development",
            "Everything you wanted to know about formatting text",
            "HyperLinks - Connecting Pages and Content",
            "Digital Media",
            "Displaying Data in Tables and iFrames",
            "Styling with CSS"
        ]
    },
    {
        id: "3pm9Ab",
        category: "Web development",
        image: course_images.web_dev2,
        course_name: "The Complete 2020 Fullstack Web Developer Courses",
        description: "Learn HTMl5, CSS, Javascript, Python, Wagtail CMS, PHP & MySQL from scratch!",
        rating_count: 6200,
        rating_star: 4.3,
        students: 90360,
        creator: "Kaleb Taulien",
        updated_date: "9/2023",
        lang: "english",
        actual_price: "21,450",
        discounted_price: 3640,
        what_you_will_learn: [
            "Learn Python from beginner to advanced",
            "Lots of projects, big and small!",
            "Learn PHP for server code execution",
            "Build a Login/Registration/Members-only website, just like Facebook",
            "Learn the LAMP Stack: Linux, Apache, PHP and MySQL",
            "Learn HTML5, CSS3, Vanilla JS (ES6+), Python, Wagtail CMS, PHP and MySQL all from scratch"
        ],
        content: [
            "The Ultimate HTML Developer: Introduction",
            "Getting Started",
            "Advanced HTML",
            "Text Formatting",
            "Fonts and Font styling",
            "Links and their 'states'",
            "Better selectors",
            "Positions",
            "Advanced Selectors",
            "CSS3 Introduction",
            "CSS3 Backgrounds Images",
            "CSS3 Gradients",
            "CSS3 Text Formatting",
            "CSS3 Transitions",
            "CSS3 Animations",
            "CSS3 Flexbox",
            "Responsive Web Design"
        ]
    },
    {
        id: "RuUs0x",
        category: "Web development",
        image: course_images.web_dev3,
        course_name: "Introduction To Web Development",
        description: "Are you Interested in Learning Web Development? Enroll in this Free course for a Dynamic Introduction to the profession!.",
        rating_count: 1740,
        rating_star: 4,
        students: 22309,
        creator: "Tech Learning Network, Mark lassoff",
        updated_date: "10/2023",
        lang: "english",
        actual_price: "19,500",
        discounted_price: 3200,
        what_you_will_learn: [
            "Understand the technologies used in web development",
            "Apply HTML document structure",
            "Add images to a web page",
            "Understand the HTML/CSS color model",
            "Alter CSS text properties",
            "Know the role of Javascript programming in web development",
            "Create a basic Javascript program to collect data",
            "Understand the next steps to learning professional web development skills"
        ],
        content: [
            "Tools and HTML",
            "CSS",
            "Javascript",
            "Bonus Lecture"
        ]
    },
    {
        id: "e_0hBc",
        category: "Web development",
        image: course_images.web_dev4,
        course_name: "Running a Web Development Business: The Complete Guide",
        description: "Learn how to start and grow a successful web development business. Get up and running and making sales in under a week.",
        rating_count: 1577,
        rating_star: 4.8,
        students: 33100,
        creator: "Evan Kimbrell",
        updated_date: "8/2023",
        lang: "english",
        actual_price: "24,500",
        discounted_price: 2600,
        what_you_will_learn: [
            "understand how development stacks work and pick which stack is ideal for you",
            "Decide between hiring in-house employees or contractors for your business",
            "Choose a winning combination of traits that you want your business to convey",
            "Find cheap and professional ways of creating an online presence",
            "Master the biggest platforms for contacting: Freelancer and Upwork",
            "Create and organize a professional and effective portfolio",
            "Utilize i5 different strategies to attract potential clients",
            "Use tools like Proposify and Nusii to create and streamline proposals"
        ],
        content: [
            "Introduction",
            "The Essentials",
            "Planning your strategy",
            "Finding subcontractors",
            "Building a portfolio",
            "Getting clients",
            "Building proposals",
            "Managing clients",
            "Best practices"
        ]
    },
    {
        id: "xxdfrt",
        category: "Web development",
        image: course_images.web_dev5,
        course_name: "Ultimate Web Designer & Web Developer Course",
        description: "Become a Full-Stack Web Designer in 2024 - Learn Everything from Web Design Fundamentals to Front-End Web Development",
        rating_count: 2941,
        rating_star: 4.6,
        students: 10450,
        creator: "Brad Hussey",
        updated_date: "3/2024",
        lang: "english",
        actual_price: "35,000",
        discounted_price: 10000,
        what_you_will_learn: [
            "Build 23+ Custom Web design & development projects by hand",
            "Plan, design amd code your very own self-directed website project from scratch to launch!",
            "Code websites & applications with HTML5 and CSS3",
            "Comfortably use Adobe Photoshop for photo manipulation, graphics creation & design",
            "Design a professional and modern business card in Adobe Photoshop",
            "Learn visual design fundamentals for beginners",
            "Learn how to choose the correct font combinations for your projects",
            "Design, build and manage custom database-driven websites with MySQL"
        ],
        content: [
            "Hey! Welcome to the course",
            "Introduction to visual Design for Web Designers & Web Developers",
            "Designing Websites, Graphics & Interfaces with Figma",
            "Introduction to Adobe Photoshop",
            "Introduction to Web Design (and more Photoshop)",
            "Advanced Web Design Challenge",
            "Introduction to HTML",
            "Intermediate HTML",
            "Advanced HTML & HTML5",
            "Expert HTML & HTML5"
        ]
    },
    {
        id: "x8Pg1X",
        category: "data science",
        image: course_images.data_science1,
        course_name: "Data Science A-Z: Real-Life Data Science Exercises Included",
        description: "Learn Data Science step by step through tool Analytics examples. Data Mining, Modeling, Tableau Visualization and more!",
        rating_count: 32103,
        rating_star: 4.5,
        students: 204985,
        creator: "Kirill Eremenko, Ligency Team",
        updated_date: "9/2024",
        lang: "english",
        actual_price: "45,000",
        discounted_price: 16000,
        what_you_will_learn: [
            "Successfully perform all steps in a complex Data Science project",
            "Perform Data Mining in Tableau",
            "Apply Ordinary least Squares method to Create Linear Regressions",
            "Assess the Adjusted R-Squared for all types of models",
            "Create a Multiple Linear Regression (MLR)",
            "Interpret coefficients of an MLR",
            "Use Backward Elimination, Forward Selection, and Bidirectional Elimination methods to create statistical models",
            "Read a Confusion Matrix"
        ],
        content: [
            "What is Data Science",
            "Part 1: Visualization",
            "Introduction to Tableau",
            "Advanced Data Mining with Tableau",
            "Stats Refreshers",
            "Simple Linear Regression",
            "Model maintenance",
            "SQL Programming for Data Science"
        ]
    },
    {
        id: "9Ui0L1",
        category: "data science",
        image: course_images.data_science2,
        course_name: "Machine Learning, Data Science and Deep Learning with Python",
        description: "Complete hands-on-machine learning tutorial with data science, Tensorflow, artificial intelligience, and neural networks",
        rating_count: 27687,
        rating_star: 4.5,
        students: 166929,
        creator: "Sundog Education by Frank Kane",
        updated_date: "2/2024",
        lang: ["english", "french"],
        actual_price: "46,000",
        discounted_price: 12300,
        what_you_will_learn: [
            "Build artificial neural networks with Tensorflow and keras",
            "Classify images, data, and sentiments using deep learning",
            "Data Visualization with MatPlotLib and Seaborn",
            "Classify data using K-Means clustering, Support Vector Machines (SVM), KNN, Decision Trees, Naive Rayes, and PCA",
            "Build a movie recommender system using item-based and user-based collaborative filtering",
            "Interpret coefficients of an MLR"
        ],
        content: [
            "Statistics and probability Refresher, and Python Practice",
            "Predictive Models",
            "Machine Learning with Python",
            "Recommender Systems",
            "More Data Mining and Machine Learning on Big Data",
            "Deep Learning and Neural Networks"
        ]
    },
    {
        id: "TKGumi",
        category: "data science",
        image: course_images.data_science3,
        course_name: "Data Science: Deep Learning and Neural Networks in Python",
        description: "The MOST in-depth look at neural theory for machine learning, with both pure Python and Tensorflow code",
        rating_count: 8513,
        rating_star: 4.8,
        students: 50184,
        creator: "Lazy Programmer Inc.",
        updated_date: "8/2023",
        lang: ["english", "Portuguese"],
        actual_price: "35,000",
        discounted_price: 6500,
        what_you_will_learn: [
            "Learn how Deep Learning REALLY works (not just some diagrams and magical black box code)",
            "Code a neural network from scratch in Python and numpy",
            "Describe diffrent types of neural networks and the different types of problems they are used for",
            "Create a neural network with an output that has K > 2 classes using softmax",
            "Install Tensorflow"
        ],
        content: [
            "Preliminaries: From Neurons from Neural Networks",
            "Training a neural network",
            "Practical Machine Learning",
            "Tensorflow, exercises, practice, and what to learn next",
            "Project: Facial Expression Recognition",
            "Backpropagation Supplementary Lectures",
            "Higher-Level Discussion"
        ]
    },
    {
        id: "oETsMx",
        category: "data science",
        image: course_images.data_science4,
        course_name: "R Programming A-Z: R For Data Science With Real Exercises!",
        description: "Learn Programming In And R Studio. Data Analytics, Data Science, statistical Analysis, Packages, Functions, GGPlot2",
        rating_count: 47264,
        rating_star: 4.8,
        students: 237914,
        creator: "Kirill Eremenko, Ligency Team",
        updated_date: "11/2023",
        lang: "english",
        actual_price: "41,900",
        discounted_price: 5000,
        what_you_will_learn: [
            "Learn to program in R at a good level",
            "Learn the core principles of programming",
            "Learn how to create variables",
            "Learn how to create a while() loop and a for() loop in R",
            "Learn the matrix() function, learn rbind() and cbind()",
            "Learn how to customize R studio to suit your preferences"
        ],
        content: [
            "Hit The Ground Running",
            "Core Programming Principles",
            "Fundamentals of R",
            "Matrices",
            "Data Frames",
            "Advanced Visualization with GGPlot2",
            "Homework Solutions",
        ]
    },
    {
        id: "-awjaj",
        category: "data science",
        image: course_images.data_science5,
        course_name: "Data Science and Machine Learning Bootcamp with R",
        description: "Learn how to use the R programming language for data science and machine learning and data visualization!",
        rating_count: 32103,
        rating_star: 5,
        creator: "Jose Portilla",
        updated_date: "12/2023",
        lang: ["english", "arabic"],
        actual_price: "53,000",
        discounted_price: 6700,
        what_you_will_learn: [
            "Program in R",
            "Create Data Visualization",
            "Use R to manipulate data easily",
            "Use R for Data Analysis",
            "Use R for handle csv,excel,SQL files or web scraping",
            "Use R for Machine Learning Algorithms"
        ],
        content: [
            "Course Best Practices",
            "Windows Installation Set-up",
            "Mac OS Installation Set-up",
            "Linux Installation",
            "Development Environment Overview",
            "Introduction to R Basics",
            "R Data Frames"
        ]
    },
    {
        id: "xxxbMD",
        category: "aws",
        image: course_images.aws1,
        course_name: "Amazon Web Services (AWS) Certified 2024 - 4 Certification!",
        description: "Videos, Labs & practice exams - AWS Certified (Solutions Architect, Developer, SySOps Administrator, Cloud Practitioner)",
        rating_count: 21046,
        rating_star: 4.2,
        students: 134932,
        creator: "Backspace Academy, paul Coady",
        updated_date: "12/2023",
        lang: ["english", "arabic"],
        actual_price: "34,000",
        discounted_price: 5300,
        what_you_will_learn: [
            "You will be fully prepared for the",
            "AWS Certified Solutions Architect",
            "Associate, AWS Certified Developer",
            "Associate and AWS Certified SysOps ..."
        ],
        content: [
            "HouseKeeping",
            "Infrastructure, Pricing, Support - Review",
            "Networking Printer",
            "EC2 Fundamentals",
            "Amazon Web Services Fundamentals",
            "AWS Storage Services",
            "AWS Database Services"
        ]

    },
    {
        id: "xxx20MD",
        category: "aws",
        image: course_images.aws2,
        course_name: "Introduction to Cloud Computing on AWS for Beginners [2024]",
        description: "Learn Cloud Computing Concepts and AWS Basics | Master AWS Fundamentals and Hands-on Skills on Amazon Web Services (AWS)!",
        rating_count: 29046,
        rating_star: 4.5,
        students: 134932,
        creator: "Neal Davis | AWS Certified Solutions",
        updated_date: "12/2023",
        lang: ["english", "arabic"],
        actual_price: "34,000",
        discounted_price: 5300,
        what_you_will_learn: [
            "This course covers fundamental concepts of cloud computing and is designed for absolute beginners",
            "Gain an understanding of the fundamental systems on which the cloud is based, including storage, networking, and compute",
            "Build knowledge from beginner level to advanced concepts",
            "Learn the basics of Amazon Web Services (AWS), the world's leading cloud computing platform",
            "Develop hands-on skills using core Amazon Web Services (AWS) services"
        ],
        content: [
            "Amazon Virtual Private Cloud (VPC)",
            "Amazon Elastic Compute Cloud (EC2)",
            "Amazon EC2, Auto Scaling, and Load Balancing",
            "Containers and Serverless Computing",
            "Automation and DevOps on AWS",
            "AWS Authentication and Accesss Control"
        ]
    },
    {
        id: "b2x20MD",
        category: "aws",
        image: course_images.aws3,
        course_name: "Ultimate AWS Certified Developer Associate 2024 NEW DVA-C02",
        description: "Full Practice Exam with Explanations included! PASS the Amazon Web Services Certified Developer Certification DVA-C02!",
        rating_count: 102138,
        rating_star: 4.7,
        students: 553328,
        creator: "Stephane Maarek | AWS Certified Cloud Practitioner",
        updated_date: "8/2024",
        lang: ["english", "arabic"],
        actual_price: "34,000",
        discounted_price: 5300,
        what_you_will_learn: [
            "Pass the AWS Certified Developer Associate Certification (DVA-C02)",
            "All 700+ slides available as downloadable PDF",
            "Deploy an application using Elastic Beanstalk and AWS CICD tools with full automation",
            "Write infrastructure as code using AWS CloudFormation",
            "Master the CLI, SDK and IAM security best practices in EC2",
            "Secure your entire AWS Cloud using KMS, Encryption SDK, IAM Policies & SSM"
        ],
        content: [
            "EC2 Instance Storage",
            "Route 53",
            "AWS Fundamentals: ELB + ASG",
            "AWS Fundamentals: RDS + Aurora + ElastiCache",
            "VPC Fundamentals",
            "AWS Authentication and Accesss Control"
        ]
    },
    {
        id: "b2berty",
        category: "design",
        image: course_images.design1,
        course_name: "Graphic Design Masterclass - Learn GREAT Design",
        description: "The Ultimate Graphic Design Course Which Covers Photoshop, Illustrator, InDesign, Design Theory, Branding, Logo Design",
        rating_count: "63,391",
        rating_star: 4.6,
        students: "255,702",
        creator: "Lindsay Marsh",
        updated_date:" 6/2024",
        lang: ["english", "arabic"],
        actual_price: "41,000",
        discounted_price: "5,300",
        what_you_will_learn: [
            "Learn a few of the upcoming design trends for 2022 and how to create them!",
            "NEW! Learn how to work with Photoshop Mockups to create great presentations",
            "NEW! Learn the Double Exposure Effect in Adobe Photoshop",
            "NEW! Learn How to Encourage and Spark Creativity",
            "NEW! How to properly give and receive critiques and feedback",
            "NEW! Learn about the history of graphic design styles in the last 130 years"
        ],
        content: [
            "How to Become a Graphic Designer",
            "Graphic Design Theory",
            "Adobe Photoshop - The Very Basics",
            "NEW! How to Encourage and Spark Creativity",
            "Photoshop Intermediate Tools",
            "Photoshop Editing and Manipulation - Intermediate Skills"
        ]
    },
    {
        id: "bmwe23",
        category: "design",
        image: course_images.design2,
        course_name: "Complete Web & Mobile Designer: UI/UX, Figma, +more",
        description: "Become a UX/UI Designer! Master Mobile and Web Design, User Interface + User Experience (UI/UX Design), HTML, and CSS",
        rating_count: "31,062",
        rating_star: 4.5,
        students: "155,907",
        creator: "Andrei Neagoie, Daniel Schifano",
        updated_date: "6/2024",
        lang: ["english", "arabic"],
        actual_price: "41,900",
        discounted_price: "5,300",
        what_you_will_learn: [
            "Learn UI/UX best practices using the latest trends in the industry",
            "Learn to make professional logos and design choices for all branding needs",
            "Learn to use HTML5 and CSS3 to make your designs come to life and create fully working websites",
            "Master Figma for your design needs then learn to convert your designs into a live HTML an CSS website",
            "Includes 100+ assets and premium design templates that you can keep and use to customize for all your future projects",
            "Learn best practices that takes years to learn in the design industry"
        ],
        content: [
            "Introduction",
            "Sketching",
            "Inspiration",
            "Figma Basics",
            "User Flows",
            "Sitemaps"
        ]
    },
        {
            id: "bvgFe34",
            category: "marketing",
            image: course_images.marketing1,
            course_name: "Mega Digital Marketing Course A-Z: 32 Courses in 1 + Updates",
            description: "Digital Marketing Strategy, Social Media Marketing, WordPress, SEO, ChatGPT, Email, Instagram, Facebook, YouTube, ads",
            rating_count: "17,746",
            rating_star: 4.5,
            students: "155,907",
            creator: "Pouya Eti | Digital Marketing Expert",
            updated_date: '8/2024',
            lang: ["english", "arabic"],
            actual_price: "35,000",
            discounted_price: "5,300",
            what_you_will_learn: [
                "Advanced Digital Marketing planning.",
                "Prompt engineering for marketing.",
                "Psychological marketing tactics.",
                "Build websites & online stores - no coding.",
                "Write Copy that Sells (copywriting).",
                "Email Marketing + pro strategies with AI."
            ],
            content: [
                "Market research",
                "ChatGPT fundamentals",
                "Website Creation - WordPress (Beginner)",
                "Website creation - WordPress (Intermediate)",
                "Website Creation - WordPress (Advanced)",
                "Business advice"
            ]
    },
    {
        id: "B46rtE",
        category: "marketing",
        image: course_images.marketing2,
        course_name: "The Complete Digital Marketing Course - 12 Courses in 1",
        description: "Master Digital Marketing Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Analytics & More!",
        rating_count: "174,746",
        rating_star: 4.5,
        students: "797,907",
        creator: "Rob Percival, Daragh Walsh",
        updated_date:' 11/2022',
        lang: ["english", "arabic"],
        actual_price: "41,000",
        discounted_price:  "5,300",
        what_you_will_learn: [
            "Grow a Business Online From Scratch",
            "Get Hired as a Digital Marketing Expert",
            "Psychological marketing tactics.",
            "Make Money as an Affiliate Marketer",
            "Work From Home as a Freelance Marketer"
        ],
        content: [
            "Make a Website",
            "Market Research",
            "Youtube Marketing",
            "Quora Marketing",
            "Copywriting",
            "Search Engine Optimization"
        ]
    }
]
export default courses